### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JohannesAnd** [JohannesAnd/SKWebsite#6]
- [ ] Picture size 2048x2048
- [ ] Dates and description in competition
- [ ] Time to dates in competition creation
- [ ] Sort by medal/photographer/date
- [ ] Presentation mode with fullscreen and slides
